name: Cargo testsuite

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pinelang/llvm-docker-rust:v1.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run testsuite
        run: cargo test
