name: Cargo testsuite

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pinelang/llvm-docker-rust:v1.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install LLVM
        run: bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - name: Run testsuite
        run: cargo test
